### PR TITLE
first iteration for seasons

### PR DESCRIPTION
**Pull request by dblop**
Some logic to allow for seasons. 
Changed behavior from adding +1 watched to match last watched episode number.

Might be useful, works for my series

### CODE REVIEW

**Comment by RickDB** [comment]
Looks good, for update_mal_list_with_seasons() only problem might be the additional calls to MAL (spice.search) as it could lead to an potential ban (> 250 shows here so that's a lot of searches).
Not sure what their current policy is but remember them being pretty strict.

Just let me know if you want to commit more changes otherwise can merge as-is :)

**Comment by dblop** [comment]
Yeah this could be a problem with a long list. I just made some changes to first build a view of the seasons from your own mal_list (by substring matching), and then use splice.search only on whatever is not found. Worked for me but I strongly recommend you test on yours! I don't have a list long enough to properly debug it, and I'm sure it needs some ironing out.

Working on: Overlord & Overlord 2
NOT WORKING ON: Remakes (FMA and FMA:Brotherhood, dunno how to filter this out...)

**Comment by RickDB** [comment]
Thanks, will do some testing here today.

**Comment by RickDB** [comment]
Think the tuple list got mixed up in the last commit, it returned an empty mal_list.
Added some small patches here and working fine after a few runs:

https://gist.github.com/RickDB/38761b8fe75d4aa58147e00633493074

show_in_mal_list variable added back to send_watched_to_mal() as that was missing so was always searching :)

**Comment by dblop** [comment]
I got your update and did some additional fixes:
- Properly add new series (that are new seasons so were not being added)
- Don't limit the loopkup to the lastest episode on plex, properly look for your watched with highest number

I think it's good for a merge now :) of course, better to test on your list again. (Also I jumped the gun, it should work with FMA and FMA:B going by the TVDB entry)

**Comment by RickDB** [comment]
Awesome, will do some testing tomorrow.

For the future version will look into how Python does object lists to reduce the tuple amount, that way we can insert all the required information into one or two generic list formats without having to iterate thru multiple.

**Comment by RickDB** [comment]
Merging and thanks for these improvements 👍 
If you have any more don't hesitate to add, we also have a support thread if you have any questions:

https://forums.plex.tv/discussion/305261/plexmalsync-sync-your-plex-library-to-myanimelist

**Pull request merged**
